title: "Your awesome Ohh Yeah Title"
author: Yeahhh Me, Me AND Me
email: your-email@domain.com
description: > # Soy el Cid Campeador

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
